name: Build and Test

on:
  push:
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 1

    - name: Install Rust
      run: |
        rustup toolchain install stable --component clippy
        rustup default stable

    - name: Install GNOME dependencies
      run: |
        sudo apt update
        sudo apt install -y \
          pkg-config \
          libglib2.0-dev \
          libgtk-4-dev \
          libpango1.0-dev \
          libgdk-pixbuf2.0-dev \
          libcairo2-dev \
          libgirepository1.0-dev \
          libatk1.0-dev \
          libfreetype6-dev \
          libharfbuzz-dev \
          libfontconfig1-dev \
          libadwaita-1-dev

    - name: Install AppStream CLI tools
      run: sudo apt-get install -y appstream

    - name: Validate AppData file
      run: appstreamcli validate data/*.metainfo.xml

    - name: Run clippy
      run: cargo clippy --workspace --all-targets --no-deps

    - name: Run tests
      run: cargo test -- --test-threads=1
